### ISSUE TITLE
"invalid regular expression flag s"

### ISSUE THREAD

**Issue by ghost** [DCsunset/vuetify-markdown-editor#3] opened 2020-04-11 15:37 UTC
Hi,

npm v 6.14.4

node v 13.12.0

Git cloned repo

ran `npm i && npm run serve`

Nothing works either by using the git or by importing the module to another project,

Screen hangs and I get a console error:

> [Vue warn]: Error in getter for watcher "compiled": "SyntaxError: invalid regular expression flag s"
> 
> found in
> 
>  ---> <Editor> at src/components/MarkdownEditor.vue
>         <VApp>
>           <App> at src/App.vue
>             <Root>

 Seems to point to line 226 in MarkdownEditor component:
```
let compiled = render(
				this.value,
				this.renderOptions,
				_.merge(this.renderConfig, copyConfig),
				cache
			);
```

anyone knows how to fix this?

**Comment by ghost** [comment] 2020-04-11 16:00
Umm doing global search for "new RegExp(" and removing the "s" regex flags seems to have fixed it..

But not when you use it as a module.. in which case you need to modify another use of "s" flag at /node_modules/vuetify-markdown-editor/dist/vuetify-markdown-editor.umd.js:124724

**Comment by DCsunset** [comment] 2020-04-12 15:04
It's strange because I don't have this problem after repeating your steps.
Maybe you could try to delete the `node_modules` directory and run `npm i` again?

**Comment by ghost** [comment] 2020-04-12 16:01
Done, same errors occur again.
Maybe it's because I'm using it from a nuxt project?

**Comment by DCsunset** [comment] 2020-04-14 08:29
I have set up a project using nuxt.js: https://github.com/DCsunset/vuetify-markdown-editor-demo.
But still, this error doesn't occur.
It would be easier to debug if you could set up a demo project to reproduce it.

**Comment by ghost** [comment] 2020-04-15 15:47
Can you try opening a project with `npx create-nuxt-app` and use you're editor anywhere?
Fixing the "S" flags was ok for development, but now in a nuxt build the object doesn't even show up!

**Comment by ghost** [comment] 2020-04-15 15:52
The demo you linked does not work for me, same issues as I've described.

**Comment by jusantana** [comment] 2020-04-18 00:01
I'm having the same issue also. New to vue and vuetify, not sure how to fix this.

**Comment by ghost** [comment] 2020-04-18 03:16
I ended up just using [vue-simplemde](url) which is a bit less pretty but surely does the job

**Comment by DCsunset** [comment] 2020-04-18 03:20
After some tests, I have found the error.
It's because the regex uses a feature not compatible with some browsers.
Now the lastest commit should fix this error.

If it is fixed in your environment, I could publish a new version of this package.

**Comment by ghost** [comment] 2020-04-18 09:34
Works good in chrome, same errors in firefox on mac
also, if you plan to leave the nuxt example, make sure it's inside <client-only> tags, since it's not working if SSR'd (no document)

**Comment by DCsunset** [comment] 2020-04-18 12:53
@tomelic The latest commit in the master branch should already fix this issue even in Firefox, because there's no flag 's' anymore.

**Comment by DCsunset** [comment] 2020-04-27 08:14
Feel free to open the issue if this error occurs again.

**Closed as completed by DCsunset** 2020-04-27 08:14 UTC
Labels: bug
